spring:
  application:
    name: first-service
server:
  port: 8081


# Setup security
security:
  auth:
    endpoints:
      endpoint1:
        path: /myfirst/**
        methods: GET
        roles: API_READ
    users:
      userA:
        encoding: bcrypt
        password: $2a$10$n5v7onFOS0h2V2oLmyqK9uJdZRHpIghP2rFia86ALodCUfEwm4rme
        roles: API_READ