server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
      - id: myFirstModule
        uri: http://localhost:8081/
        predicates:
        - Path=/myfirst/**
      - id: mySecondModule
        uri: http://localhost:8082/
        predicates:
        - Path=/mySecond/**